### ISSUE TITLE
Export log crash

### ISSUE THREAD

**Issue by islam2hamy** [DUpdateSystem/UpgradeAll#222]
FATAL EXCEPTION: main
Process: net.xzos.upgradeall, PID: 9771
java.lang.RuntimeException: Unable to start activity ComponentInfo{net.xzos.upgradeall/net.xzos.upgradeall.ui.utils.file_pref.SaveFileActivity}: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/plain (has extras) }
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2723)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2784)
	at android.app.ActivityThread.-wrap12(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1523)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)
Caused by: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.CREATE_DOCUMENT cat=[android.intent.category.OPENABLE] typ=text/plain (has extras) }
	at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:1816)
	at android.app.Instrumentation.execStartActivity(Instrumentation.java:1525)
	at android.app.Activity.startActivityForResult(Activity.java:4398)
	at androidx.activity.ComponentActivity.startActivityForResult(SourceFile)
	at c0.b$b.b(SourceFile)
	at androidx.activity.ComponentActivity$b.c(SourceFile:8)
	at androidx.activity.result.ActivityResultRegistry$a.b(SourceFile)
	at db.a.N(SourceFile:5)
	at db.a.onCreate(SourceFile)
	at android.app.Activity.performCreate(Activity.java:6857)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2676)
	... 9 more

**Comment by islam2hamy** [comment]
com.android.documentsui is disabeld
me.zhanghai.android.files is installed

( https://github.com/zhanghai/MaterialFiles )

**Comment by JohnsonRan** [comment]
> com.android.documentsui is disabeld me.zhanghai.android.files is installed
> 
> ( https://github.com/zhanghai/MaterialFiles )

is not designed to replace DocumentsUI and can't handle a number of functionalities in DocumentsUI
https://github.com/zhanghai/MaterialFiles#inclusion-in-custom-roms
So you must enable that

**Comment by islam2hamy** [comment]
Can i trust com.android.documentsui ?

**Comment by JohnsonRan** [comment]
@islam2hamy Bro,thats a app from AOSP,can you trust AOSP?

**Comment by islam2hamy** [comment]
Ok , thank you
