### ISSUE TITLE
First update crash

### ISSUE THREAD

**Issue by islam2hamy** [DUpdateSystem/UpgradeAll#223]
Hi ,
Please find attached
[Log.txt](https://github.com/DUpdateSystem/UpgradeAll/files/9125467/Log.txt)

**Comment by JohnsonRan** [comment]
Have you tried latest build in our Telegram CI channel?

**Comment by islam2hamy** [comment]
No

**Comment by islam2hamy** [comment]
Dont have Telegram

**Comment by JohnsonRan** [comment]
https://t.me/upallci/366?single
Try download it from here

**Comment by islam2hamy** [comment]
Crash
[Log2.txt](https://github.com/DUpdateSystem/UpgradeAll/files/9125753/Log2.txt)

**Comment by islam2hamy** [comment]
FATAL EXCEPTION: main
Process: net.xzos.upgradeall.debug, PID: 20133
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 3960 free bytes and 3KB until OOM
	at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
	at java.lang.StringFactory.newEmptyString(StringFactory.java:41)
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:904)
	at java.lang.StringBuilder.substring(StringBuilder.java)
	at java.lang.AbstractStringBuilder.substring(AbstractStringBuilder.java:850)
	at java.lang.StringBuilder.substring(StringBuilder.java)
	at android.icu.impl.LocaleIDParser.getString(LocaleIDParser.java:92)
	at android.icu.impl.LocaleIDParser.getVariant(LocaleIDParser.java:480)
	at android.icu.util.ULocale.base(ULocale.java:3779)
	at android.icu.util.ULocale.getVariant(ULocale.java:911)
	at android.icu.util.Currency.createCurrency(Currency.java:224)
	at android.icu.util.Currency.getInstance(Currency.java:159)
	at android.icu.util.Currency.getInstance(Currency.java:145)
	at java.util.Currency.getInstance(Currency.java:131)
	at java.text.DecimalFormatSymbols.initialize(DecimalFormatSymbols.java:623)
	at java.text.DecimalFormatSymbols.<init>(DecimalFormatSymbols.java:96)
	at java.text.DecimalFormatSymbols.getInstance(DecimalFormatSymbols.java:159)
	at java.util.Formatter.getZero(Formatter.java:2254)
	at java.util.Formatter.<init>(Formatter.java:1880)
	at java.util.Formatter.<init>(Formatter.java:1901)
	at java.lang.String.format(String.java:2626)
	at net.xzos.upgradeall.ui.home.MainActivity$renewUpdateStatus$1.invoke(MainActivity.kt:152)
	at net.xzos.upgradeall.ui.home.MainActivity$renewUpdateStatus$1.invoke(MainActivity.kt:149)
	at net.xzos.upgradeall.core.androidutils.UtilsKt.runUiFun$lambda-0(Utils.kt:40)
	at net.xzos.upgradeall.core.androidutils.UtilsKt.$r8$lambda$BnHZUAXpStmdYKx5lmBnYYSP9kE(Utils.kt)
	at net.xzos.upgradeall.core.androidutils.UtilsKt$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
	at android.os.Handler.handleCallback(Handler.java:754)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:163)
	at android.app.ActivityThread.main(ActivityThread.java:6238)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:933)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by islam2hamy** [comment]
FATAL EXCEPTION: OkHttp TaskRunner
Process: net.xzos.upgradeall.debug, PID: 20133
java.lang.OutOfMemoryError: Failed to allocate a 28 byte allocation with 3960 free bytes and 3KB until OOM
	at okio.RealBufferedSource.require(RealBufferedSource.kt:199)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:90)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:102)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

**Comment by xz-dev** [comment]
@islam2hamy Which Phone, which OS

**Comment by islam2hamy** [comment]
Miui 11.0.2
Android 7.1.2

**Comment by xz-dev** [comment]
@xz-dev Disable unnecessary application mode, and "auto update data on open"

**Comment by islam2hamy** [comment]
[Log14.txt](https://github.com/DUpdateSystem/UpgradeAll/files/9125896/Log14.txt)

**Comment by JohnsonRan** [comment]
@islam2hamy Looks like it's your network issue.

And we highly recommend you to report bugs to our Telegram discussion group,so that we can reply you faster.

**Comment by islam2hamy** [comment]
> @islam2hamy Looks like it's your network issue.
> 
P.s : i am using dnscrypt 
( https://f-droid.org/packages/pan.alexander.tordnscrypt.stable/ )
> Here are some suggestions:
> 
> First, Please don't send files or directly copy&paste logs here,it's really annoying and unreadable, please use some network pasteboard like [nekobin](https://nekobin.com).Thanks!
> 
Ok , next time
> Second, we highly recommend you to report bugs to our Telegram discussion group,so that we can reply you faster.

Sorry not using Telegram

**Comment by islam2hamy** [comment]
With no dnscrypt
[Log1-1.txt](https://github.com/DUpdateSystem/UpgradeAll/files/9126860/Log1-1.txt)

**Comment by xz-dev** [comment]
That's OOM, I'm sure that can fix it. https://github.com/DUpdateSystem/UpgradeAll/issues/240#issuecomment-1206587685
