### ISSUE TITLE
keeps crashing 

### ISSUE THREAD

**Issue by rajarshikhatua100** [DUpdateSystem/UpgradeAll#242]
the app keeps crashing in its latest Alpha version ie. alpha 5 
here's the log -
FATAL EXCEPTION: main
Process: net.xzos.upgradeall, PID: 25406
java.lang.RuntimeException: Unable to create application net.xzos.upgradeall.application.MyApplication: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7511)
	at android.app.ActivityThread.access$1600(ActivityThread.java:310)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2281)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8663)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:567)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1135)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
	at d9.d$a.a(SourceFile:1)
	at b9.d.a(SourceFile:7)
	at b9.b.<init>(SourceFile:3)
	at z8.a.f(SourceFile:24)
	at z8.d.r(Unknown Source:12)
	at c7.a.j(Unknown Source:8)
	at s7.g0.run(SourceFile:4)
	at s7.n0.t0(SourceFile:4)
	at g7.a.o(SourceFile:13)
	at g7.a.p(Unknown Source:2)
	at y9.b.f(SourceFile:37)
	at net.xzos.upgradeall.application.MyApplication.onCreate(SourceFile:22)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1211)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7506)
	... 9 more

**Comment by xz-dev** [comment]
@rajarshikhatua100 Your ROM and phone model

**Comment by xz-dev** [comment]
Also, can you record the screen?

**Comment by islam2hamy** [comment]
#223

**Comment by rajarshikhatua100** [comment]
sorry for the late I am using
Samsung galaxy m31
one ui core 3.1
Android 12
here is the screen recording

https://user-images.githubusercontent.com/77912617/184012719-4deead8e-9fbf-479f-98ae-6b9df3c01449.mp4

**Comment by rajarshikhatua100** [comment]
you can't also see the logs created by scoop app and problem diagnosed by system 

https://user-images.githubusercontent.com/77912617/184013567-fb167e28-5999-4e55-b831-d952cffc3561.mp4

**Comment by xz-dev** [comment]
> #223

You can try this way https://github.com/DUpdateSystem/UpgradeAll/issues/240#issuecomment-1206587685

**Comment by xz-dev** [comment]
> you can't also see the logs created by scoop app and problem diagnosed by system
> recording_20220808_134702_002.mp4

ok，we got it, we will try to fix

**Comment by rajarshikhatua100** [comment]
thanks for the solution

**Comment by xz-dev** [comment]
By the way, which APPs or application mode have you added?
